In [3]:
import torch
import torch.nn as nn

# 一 基本用法

定义Embedding，词表大小为10，每个词使用一个5维的向量表示

In [35]:
embedding = nn.Embedding(num_embeddings=10, embedding_dim=5)
embedding.weight.data

tensor([[ 1.3984, -0.4209,  0.1604, -2.8658,  0.9689],
        [ 0.0831, -0.1645,  0.6297, -0.1716, -0.9245],
        [-1.1768,  0.8850, -0.8981, -0.5477,  0.3135],
        [ 1.0204, -0.7484, -0.9276, -0.2204, -0.6722],
        [ 0.0316,  1.9520,  0.7206,  0.4960, -0.4515],
        [ 1.4720,  1.5039, -1.8053,  0.8424,  0.5210],
        [ 1.2036, -1.3512,  0.4166,  1.5348,  1.0912],
        [ 0.1018,  0.6452,  1.3158,  0.8136,  0.2035],
        [ 0.8335,  0.5776, -0.4083, -0.7707,  0.9449],
        [ 0.3078,  1.0718,  0.1940,  1.0429, -1.2746]])

In [39]:
input = torch.tensor(0)
output = embedding(input)
print(input.shape)
print(output)
print(output.shape)

torch.Size([])
tensor([ 1.3984, -0.4209,  0.1604, -2.8658,  0.9689],
       grad_fn=<EmbeddingBackward0>)
torch.Size([5])


In [40]:
input = torch.tensor([0])
print(input.shape)
output = embedding(input)
print(output)
print(output.shape)

torch.Size([1])
tensor([[ 1.3984, -0.4209,  0.1604, -2.8658,  0.9689]],
       grad_fn=<EmbeddingBackward0>)
torch.Size([1, 5])


In [41]:
input = torch.tensor([0, 1, 2])
print(input.shape)
output = embedding(input)
print(output)
print(output.shape)

torch.Size([3])
tensor([[ 1.3984, -0.4209,  0.1604, -2.8658,  0.9689],
        [ 0.0831, -0.1645,  0.6297, -0.1716, -0.9245],
        [-1.1768,  0.8850, -0.8981, -0.5477,  0.3135]],
       grad_fn=<EmbeddingBackward0>)
torch.Size([3, 5])


In [42]:
input = torch.tensor([[0, 1, 2]])
print(input.shape)
output = embedding(input)
print(output)
print(output.shape)

torch.Size([1, 3])
tensor([[[ 1.3984, -0.4209,  0.1604, -2.8658,  0.9689],
         [ 0.0831, -0.1645,  0.6297, -0.1716, -0.9245],
         [-1.1768,  0.8850, -0.8981, -0.5477,  0.3135]]],
       grad_fn=<EmbeddingBackward0>)
torch.Size([1, 3, 5])


In [43]:
input = torch.tensor([[0, 1, 2],[3, 4, 5]])
print(input.shape)
output = embedding(input)
print(output)
print(output.shape)

torch.Size([2, 3])
tensor([[[ 1.3984, -0.4209,  0.1604, -2.8658,  0.9689],
         [ 0.0831, -0.1645,  0.6297, -0.1716, -0.9245],
         [-1.1768,  0.8850, -0.8981, -0.5477,  0.3135]],

        [[ 1.0204, -0.7484, -0.9276, -0.2204, -0.6722],
         [ 0.0316,  1.9520,  0.7206,  0.4960, -0.4515],
         [ 1.4720,  1.5039, -1.8053,  0.8424,  0.5210]]],
       grad_fn=<EmbeddingBackward0>)
torch.Size([2, 3, 5])


# 二 Padding

In [46]:
embedding = nn.Embedding(num_embeddings=10, embedding_dim=5, padding_idx=0)
embedding.weight.data

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.6281, -0.5121, -0.0934,  1.8779, -1.2897],
        [-1.2710,  1.0979, -0.4348,  1.5668, -0.4396],
        [ 0.8175,  1.1931, -0.4601, -1.1399, -0.7381],
        [ 1.0116, -0.1747,  0.6771, -0.1142, -0.6856],
        [-0.9729,  1.5503,  0.1485, -0.4700,  0.2581],
        [ 1.2010, -0.8075,  0.7782, -0.6551,  0.0872],
        [-0.3961,  0.7829, -0.6239,  0.4448,  1.0049],
        [ 0.1219, -0.8450, -0.5033,  0.1470, -1.4151],
        [ 0.3868, -0.1336,  1.2232, -1.8347, -0.1270]])

In [45]:
input = torch.tensor([[0, 1, 2], [0, 0, 3]])
print(input.shape)
output = embedding(input)
print(output)
print(output.shape)

torch.Size([2, 3])
tensor([[[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [-0.3829, -1.1299,  2.1888, -0.7058,  1.3499],
         [-0.6019, -1.0834, -0.3234,  0.4496,  0.7212]],

        [[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [-1.4040, -0.3218,  0.9971, -1.9596,  1.2746]]],
       grad_fn=<EmbeddingBackward0>)
torch.Size([2, 3, 5])
