# Tensor 创建

In [10]:
import torch
import numpy as np

## 一 使用随机值或常量值

### 1.1 使用随机值

In [11]:
shape = (2, 2,)
tensor_rand = torch.rand(shape)
tensor_rand

tensor([[0.9598, 0.6502],
        [0.8963, 0.4388]])

### 1.2 使用常量0

In [12]:
shape = (3, 3,)
tensor_zeros = torch.zeros(shape)
tensor_zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### 1.3 使用常量1

In [13]:
shape = (3, 2,)
tensor_ones = torch.ones(shape)
tensor_ones

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

## 二 直接从数据创建

In [14]:
data = [[1, 2], [3, 4]]
tensor_data = torch.tensor(data)
tensor_data

tensor([[1, 2],
        [3, 4]])

## 三 从另一个张量创建

In [15]:
tensor_rand_like = torch.rand_like(tensor_zeros)
tensor_rand_like

tensor([[0.7947, 0.2266, 0.3840],
        [0.2405, 0.6984, 0.0199],
        [0.1924, 0.3674, 0.2453]])

In [16]:
tensor_zeros_like = torch.zeros_like(tensor_ones)
tensor_zeros_like

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [17]:
tensor_ones_like = torch.ones_like(tensor_rand)
tensor_ones_like

tensor([[1., 1.],
        [1., 1.]])

## 四 从 NumPy array

In [18]:
np_data = [[1, 2], [3, 4]]
np_array = np.array(np_data)
np_array

array([[1, 2],
       [3, 4]])

In [19]:
tensor_numpy = torch.from_numpy(np_array)
tensor_numpy

tensor([[1, 2],
        [3, 4]])